"""add chart_data to GameRounds

Revision ID: 3c827d456cd5
Revises: 6f3d3da4c341
Create Date: 2026-01-26 15:22:00.986290

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c827d456cd5"
down_revision: Union[str, Sequence[str], None] = "6f3d3da4c341"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_rounds", sa.Column("chart_data", sa.JSON(), nullable=True))
    op.execute(
        'UPDATE game_rounds SET chart_data = \'{"before":[], "after":[]}\' WHERE chart_data IS NULL'
    )
    op.alter_column("game_rounds", "chart_data", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_rounds", "chart_data")
    # ### end Alembic commands ###
