"""add points to User and is_won,earned_points to Prediction

Revision ID: 6f3d3da4c341
Revises: ddaa6463372e
Create Date: 2026-01-21 12:59:27.110428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f3d3da4c341"
down_revision: Union[str, Sequence[str], None] = "ddaa6463372e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # predictions - is_won
    op.add_column("predictions", sa.Column("is_won", sa.Boolean(), nullable=True))

    # predictions - earned_points
    op.add_column(
        "predictions", sa.Column("earned_points", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE predictions SET earned_points = 0")
    op.alter_column("predictions", "earned_points", nullable=False)

    # users - points
    op.add_column("users", sa.Column("points", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET points = 1000")
    op.alter_column("users", "points", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "points")
    op.drop_column("predictions", "earned_points")
    op.drop_column("predictions", "is_won")
    # ### end Alembic commands ###
